/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package information;

import java.awt.Rectangle;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;

/**
 *
 * @author monkeyboz
 */
public class ServersList extends javax.swing.JLayeredPane {
    VBox parent;
    TreeModel ServerList;
    int[] mouseOrigin;
    
    /**
     * Creates new form ServerList
     */
    public ServersList(VBox parent) {
        setParent(parent);
        initComponents();
        
        //setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
    }
    
    public void setupParent(VBox parent){
        this.parent = parent;
    }
    
    public void setupServerModel(){
        DefaultMutableTreeNode servers = new DefaultMutableTreeNode("servers");
        this.parent.setupVBoxDir();
        ArrayList<String> serversHolder = this.parent.getServers();
        for(int i = 0; i < serversHolder.size(); ++i){
            DefaultMutableTreeNode currServer = new DefaultMutableTreeNode(serversHolder.get(i));
            String[] tmpServer = this.parent.getVMList(i).split(",");
            for(int j = 0; j < tmpServer.length; ++j){
                if(tmpServer[j] != "null"){
                    DefaultMutableTreeNode serverInfo = new DefaultMutableTreeNode(tmpServer[j]);
                    currServer.add(serverInfo);
                }
            }
            servers.add(currServer);
        }
        DefaultTreeModel model = new DefaultTreeModel(servers);
        jTree1.setModel(model);
        
        jTree1.setCellRenderer(new CellRenderer());
        this.setVisible(true);
    }
    
    public void setParent(VBox parent){
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jLayeredPane1.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLayeredPane1.setOpaque(true);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Server List");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTree1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTree1);

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, parent.getWidth()-50, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, parent.getHeight()-120, Short.MAX_VALUE)
                .addContainerGap())
        );
        setLayout();
    }// </editor-fold>
    
    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        if(jTree1.getSelectionPaths() != null){
            String[] info = jTree1.getSelectionPaths()[0].toString().replace("[","").replace("]","").split(",");
            String osInfo = info[info.length-1].substring(1).replace("\"","").trim();
            String[] extract = osInfo.split(" ");
            String commandString = "";
            if(extract.length > 1){
                for(int i = 0; i < extract.length-1; ++i){
                    commandString += extract[i]+" ";
                }
                String startedVM = commandString.substring(0,commandString.length()-1);
                String[] testing = new String[]{parent.getVBDir(),"startvm","\""+startedVM+"\""};
                parent.setStartedVM(startedVM);
                parent.runCommand(testing,true,"startVM",true,"Starting VM");
            }
        }
    }     
    
    public void setLayout(){
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(parent.getJPanel2());
        parent.jPanel2SetLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        setupServerModel();
    }

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {                                     
        Runtime.getRuntime().halt(0);
    }                               

    private void formMousePressed(java.awt.event.MouseEvent evt) {                                  
        mouseOrigin = new int[]{evt.getX(),evt.getY()};
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration                   
}
